#!/opt/local/bin/bash

if [[ -z ${1} ]]; then
  echo "call with the regex for the gate you want to connect to"
  exit 1
fi

IDENT=""
if [[ ! -z ${3} ]]; then
  IDENT="-i ${3}"
fi

USERENT="--login root"
if [[ ! -z ${4} ]]; then
  USERENT="--login ${4}"
fi

nova ssh ${USERENT} ${IDENT} --extra-opts '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o TCPKeepAlive=yes' ${1}
