#!/opt/local/bin/bash

if [[ -z ${1} ]]; then
  echo "call with the regex for the cluster you want to connect to"
  exit 1
fi

export LC_CTYPE=C
RANDOM_NUM=$(cat /dev/urandom | tr -dc '0-9' | head -c 4)
SCREEN_SESSION="cloud-connect-${RANDOM_NUM}"

#ENVFILE="~/.cloud10-cloudserversrc"
#if [[ ! -z ${2} ]]; then
#  ENVFILE="${2}"
#fi

USERENT="--login root"
if [[ ! -z ${2} ]]; then
  USERENT="--login ${2}"
fi

SSH_PUBKEY=""
if [[ ! -z ${3} ]]; then
  SSH_PUBKEY="-i ${3}"
fi

echo "getting the list of nodes matching ${1}.  Hit CTRl-C if that isn't what you wanted"

if type -p screen >/dev/null && screen -ls | egrep -q "[0-9].$SCREEN_SESSION"; then
  echo "You are already running a session."
  echo "To rejoin this session type 'screen -x ${SCREEN_SESSION}'."
  exit 1
fi

NL=`echo -ne '\015'`

screen -d -m -S ${SCREEN_SESSION} -t shell -s /bin/bash
screen -r ${SCREEN_SESSION} -X hardstatus string "%{.bW}%-w%{.rW}%n %t%{-}%+w %=%{..G} %H %{..Y} %d/%m %C%a "
screen -r ${SCREEN_SESSION} -X defscrollback 10000
screen -r ${SCREEN_SESSION} -X setenv PROMPT_COMMAND /bin/true

for i in $(nova list --name ${1} --fields name | awk '{print $4}' | grep "${1}"); do
  screen -S ${SCREEN_SESSION} -X screen -t $i
#  screen -S ${SCREEN_SESSION} -p $i -X stuff "bash -c \". ${ENVFILE}; nova ssh ${USERENT} ${SSH_PUBKEY} --extra-opts '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o TCPKeepAlive=yes' ${i}\"$NL"
  screen -S ${SCREEN_SESSION} -p $i -X stuff "bash -c \"nova ssh ${USERENT} ${SSH_PUBKEY} --extra-opts '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o TCPKeepAlive=yes' ${i}\"$NL"
done
screen -S ${SCREEN_SESSION} -p shell -X stuff "exit$NL"

if [[ ${COUNTER} = 0 ]]; then
  echo "no nodes found matching ${1}"
  exit 1
fi

screen -r ${SCREEN_SESSION}
